### PR TITLE
fixed a few things

### PR DESCRIPTION
**Pull request by hhuang97**
Completed merge function for quadtree, integrated that with npc so that collision detection is faster by utilizing both rectangle intersect and circle intersect. Added collision detection separately to enemy and friendly. Resolved miscellaneous merge conflicts.

### CODE REVIEW

**Comment by benjamincongdon** [comment]
Just so you know, you don't need to make new pull requests if you're pushing to the same branch. As long as the request has not yet been merged, new commits on that branch will automatically be put into the request.

**Comment by benjamincongdon** [comment]
Also, is this ready to be merged?

**Comment by hhuang97** [comment]
With the original implementation of the quadtree, yes. But I'm fixing the quadtree so don't merge until that's complete and re-integrated

**Comment by sebmathguy** [comment]
The existing game code needs to be modified to use a wrapper for this functionality.

**Pull request closed without merging**
