### PR TITLE
Pulling develop over to my branch

### PR DESCRIPTION
**Pull request by gragas**
So I can work with the hackathon additions.

### CODE REVIEW

**Comment by gragas** [comment]
Also, get in Google Hangouts. Or we should use Slack's chat.

**Comment by benjamincongdon** [comment]
What was the slack domain again?

**Comment by gragas** [comment]
portocinidelfuego.slack.com

**Comment by benjamincongdon** [comment]
I think you need to add me to the domain. I'll text you my email

**Comment by gragas** [comment]
We should really get a new domain. I'll text it to you.

**Comment by benjamincongdon** [comment]
K

**Pull request merged**
